name: 'Setup coscli environment'
description: 'Download and config Tencent Cloud coscli'
author: 'git9527'
inputs:
  region:
    description: 'The region of your bucket'
    required: true
  secret-id:
    description: 'The Secret ID of the credentials'
    required: true
  secret-key:
    description: 'The Secret Key of the credentials'
    required: true
  bucket:
    description: 'The Bucket of target operation'
    required: true
  session-token:
    description: 'The Session Token of the credentials, Optional'
    required: false
  coscli-version:
    description: 'The coscli version to download and use'
    required: false
    default: 'v0.12.0-beta'
  github-token:
    description: 'The GitHub token used to call API to fetch the latest version info'
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'download-cloud'
  color: 'orange'
