name: "build"
on: # rebuild any PRs and main branch changes
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        github-token: ${{ github.token }}
    - run: npm ci
    - run: npm run all
    - name: upload the expected dist
      uses: actions/upload-artifact@v3
      if: ${{ failure() && steps.diff.conclusion == 'failure' }}
      with:
        name: dist
        path: dist/
