name: "test"
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  test: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [v0.12.0-beta]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      timeout-minutes: 2
      with:
        region: ${{ secrets.COS_REGION }}
        secret-id: ${{ secrets.COS_SECRET_ID }}
        secret-key: ${{ secrets.COS_SECRET_KEY }}
        coscli-version: ${{ matrix.version }}
    - run: coscli -v
    - run: coscli ls > /dev/null
      shell: bash
